# Generated by Django 4.0.2 on 2023-02-10 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottomwearprice', models.CharField(blank=True, max_length=100, null=True)),
                ('topwearprice', models.CharField(blank=True, max_length=100, null=True)),
                ('woolenprice', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topwearqty', models.CharField(blank=True, max_length=100, null=True)),
                ('bottomwearqty', models.CharField(blank=True, max_length=100, null=True)),
                ('woolenclothqty', models.CharField(blank=True, max_length=100, null=True)),
                ('other', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, default='New', max_length=100, null=True)),
                ('servicetype', models.CharField(blank=True, max_length=100, null=True)),
                ('contactperson', models.CharField(blank=True, max_length=100, null=True)),
                ('pickupaddress', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('todate', models.CharField(blank=True, max_length=100, null=True)),
                ('fromdate', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('other_price', models.CharField(blank=True, max_length=100, null=True)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laundryapp.register')),
            ],
        ),
    ]
